lib/handlers/passwordReset/SAResetV1.js, lib/handlers/passwordReset/index.js, lib/infrastructure/templates/renderTemplates/sa-reset-password/email/html.ejs, lib/infrastructure/templates/renderTemplates/sa-reset-password/email/text.ejs, package-lock.json, test/handlers/passwordResetTests/SAResetV1.test.js
Email for unmigrated SA user attempting to reset password
=> NSA-1567- unmigrated Sa user email

lib/handlers/support/index.js, lib/handlers/support/supportRequestConfirmationV1.js, lib/infrastructure/templates/renderTemplates/support-request-confirmation/email/html.ejs, lib/infrastructure/templates/renderTemplates/support-request-confirmation/email/text.ejs, test/handlers/supportTests/supportRequestConfirmationV1.test.js
Automated email to send to users when they send a support request
=> Nsa 1723 support  confirmation email

lib/infrastructure/templates/renderTemplates/sa-reset-password/email/html.ejs, lib/infrastructure/templates/renderTemplates/sa-reset-password/email/text.ejs
Updated content of SA password reset email to include details of how to migrate
=> Updated email content for Sa password reset

lib/handlers/support/supportRequestV1.js, lib/infrastructure/templates/renderTemplates/support-request/email/html.ejs, lib/infrastructure/templates/renderTemplates/support-request/email/text.ejs, test/handlers/supportTests/supportRequestV1.test.js
=> NSA-1764- webform update

lib/handlers/unmigratedSaUser/index.js, lib/handlers/unmigratedSaUser/unmigratedSaUserV1.js, lib/infrastructure/templates/renderTemplates/unmigrated-sa-user/email/html.ejs, lib/infrastructure/templates/renderTemplates/unmigrated-sa-user/email/text.ejs, test/handlers/unmigratedSaUser/index.test.js, test/handlers/unmigratedSaUser/unmigratedSaUserV1.test.js
Send migration instructions email to an sa user if they enter a recognised sa email but have not yet migrated their account
=> Unmigrated sa user email

lib/handlers/serviceAdded/index.js, lib/handlers/serviceAdded/newServiceAddedV1.js, lib/index.js, lib/infrastructure/templates/renderTemplates/user-service-added/email/html.ejs, lib/infrastructure/templates/renderTemplates/user-service-added/email/text.ejs, test/handlers/serviceAdded/index.test.js, test/handlers/serviceAdded/newServiceAddedV1.test.js
Email notification when a user has a new service added.
=> NSA-2194 - new service added email

lib/handlers/accessRequest/index.js, lib/handlers/accessRequest/organisationRequestHanderV1.js, lib/handlers/accessRequest/userAccessRequestV1.js, lib/infrastructure/templates/renderTemplates/user-access-request-email/email/html.ejs, lib/infrastructure/templates/renderTemplates/user-access-request-email/email/text.ejs, test/handlers/accessRequest/organisationRequestHandlerV1.test.js, test/handlers/accessRequest/userAccessRequestV1.test.js
Confirmation email to send to user when they have requested an org
=> NSA-2374- confirmation email for request

lib/infrastructure/templates/renderTemplates/access-request-email/email/html.ejs, lib/infrastructure/templates/renderTemplates/access-request-email/email/text.ejs
NSA-2454 Approver Organisation Request - Share Rejection Reason
=> NSA-2454 Approver Organisation Request - Share Rejection Reason

lib/handlers/accessRequest/approverAccessRequestV1.js, lib/handlers/accessRequest/organisationRequestHanderV1.js, test/handlers/accessRequest/approverAccessRequestV1.test.js, test/handlers/accessRequest/organisationRequestHandlerV1.test.js
NSA-2401 Organisation Request Email link to Requests Page
=> NSA-2401 Organisation Request Email link to Requests Page

lib/handlers/invite/newUserInvitationV2.js, lib/infrastructure/templates/renderTemplates/invitation/email/html.ejs
=> NSA-2149-CSS-Style

lib/infrastructure/templates/renderTemplates/invitation/email/html.ejs
=> NSA-2150 email template fix

lib/handlers/invite/newUserInvitationV1.js
=> NSA-2704 Add 'Verification Code' to the 'Subject' of 'Verification Email'

lib/handlers/invite/newUserInvitationV1.js, lib/handlers/invite/newUserInvitationV2.js, test/handlers/invitationTests/newUserInvitationV2.test.js
=> NSA-2704-correction

lib/infrastructure/templates/renderTemplates/user-added-to-organisation/email/html.ejs, lib/infrastructure/templates/renderTemplates/user-added-to-organisation/email/text.ejs, lib/infrastructure/templates/renderTemplates/user-persmission-level-changed/email/html.ejs, lib/infrastructure/templates/renderTemplates/user-persmission-level-changed/email/text.ejs, lib/infrastructure/templates/renderTemplates/user-removed-from-organisation/email/html.ejs, lib/infrastructure/templates/renderTemplates/user-removed-from-organisation/email/text.ejs
=> NSA-2681 User Notification Of Changes

lib/handlers/invite/newUserInvitationV1.js, lib/handlers/invite/newUserInvitationV2.js, lib/handlers/passwordReset/passwordResetV1.js, lib/handlers/registration/registerExistingUserV1.js, lib/infrastructure/email/DiskEmailAdapter.js, lib/infrastructure/email/S3EmailAdapter.js, lib/infrastructure/email/SESEmailAdapter.js, lib/infrastructure/email/index.js, test/infrastructure/emailtests/DiskEmailAdapter.test.js, test/infrastructure/emailtests/S3EmailAdapter.test.js
Information and exception logging has been added to tract the email failures
=> PR-feature-4706-Add Logging when sending an email

lib/handlers/passwordReset/passwordResetV1.js, lib/infrastructure/templates/renderTemplates/password-reset/email/html.ejs, lib/infrastructure/templates/renderTemplates/password-reset/email/text.ejs, package-lock.json, package.json, test/handlers/passwordResetTests/passwordResetV1.test.js
Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-6539
=> NSA-6539 - updated password reset email templates

.eslintrc, .prettierrc, lib/handlers/subServiceRequestActioned/index.js, lib/handlers/subServiceRequestActioned/subServiceRequestApproved.js, lib/handlers/subServiceRequestActioned/subServiceRequestRejected.js, lib/handlers/subServiceRequested/index.js, lib/handlers/subServiceRequested/subServiceRequestToApprovers.js, lib/index.js, lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/text.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-rejected/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-rejected/email/text.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-to-approvers/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-to-approvers/email/text.ejs, package-lock.json, package.json, test/handlers/serviceRequested/serviceRequestToApproversV2.test.js, test/handlers/subServiceRequestActioned/index.test.js, test/handlers/subServiceRequestActioned/subServiceRequestApproved.test.js, test/handlers/subServiceRequestActioned/subServiceRequestRejected.test.js, test/handlers/subServiceRequested/index.test.js, test/handlers/subServiceRequested/subServiceRequestToApprovers.test.js, test/utils.js
Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-6856
=> [NSA-6856] Add notifications emails for end user sub-services requests

lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/text.ejs
[NSA](https://dfe-secureaccess.atlassian.net/browse/NSA-7109)
made changes to the sub-service approved email both html and text
=> finished work

lib/handlers/subServiceRequestActioned/subServiceRequestApproved.js
spoke with Matt he said if its pluralised now keep it that way
=> checking in for review

lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-approved/email/text.ejs
found a <br> in text portion of the email
=> removed <br> from text template

package.json
=> update to pre-release version

lib/handlers/accessRequest/approverAccessRequestV1.js, package-lock.json, package.json, test/handlers/accessRequest/approverAccessRequestV1.test.js, test/handlers/invitationTests/newUserInvitationV2.test.js, test/handlers/subServiceRequestActioned/subServiceRequestApproved.test.js
https://dfe-secureaccess.atlassian.net/browse/NSA-7246 Fixing wrongly constructed URI in approver request emails.
=> NSA-7246: Fixed broken org request link and tests

lib/infrastructure/templates/renderTemplates/sub-service-request-to-approvers/email/html.ejs
=> fixed to testers comment

lib/infrastructure/templates/renderTemplates/sub-service-request-to-approvers/email/html.ejs, lib/infrastructure/templates/renderTemplates/sub-service-request-to-approvers/email/text.ejs
added to html and text Give a reason for rejection and reject the request.
=> fixed sentence

lib/handlers/support/supportOverdueRequest.js, lib/infrastructure/templates/renderTemplates/support-overdue-request/email/html.ejs, lib/infrastructure/templates/renderTemplates/support-overdue-request/email/text.ejs, test/handlers/supportTests/supportOverdueRequest.test.js
Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7245
Changes:
-changes to the outstanding email templates and subject to toggle the content based on the requests number
=> [NSA-6737] Updates to outstanding request email templates

lib/handlers/invite/newUserInvitationV2.js, lib/handlers/serviceAdded/newServiceAddedV2.js, lib/infrastructure/email/SESEmailAdapter.js, lib/infrastructure/email/utils.js, package-lock.json, package.json, test/infrastructure/emailtests/maskEmali.test.js
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-6973
- bumped login.dfe.dao package version to fix vulnerabilities 
- added functionality to mask recipient email address in SES EmailAdapter logs 
- removed sensitive console logs
=>  [DSI-6973] Remove sensitive data logs and fix vulnerable packages
